# Dimensions to perform analysis operations in
dims: ['mz', 'drift_time', 'retention_time']

# mzML accession fields to access and name
accession: {'drift_time': 'MS:1002476',
            'retention_time': 'MS:1000016'}

# Nominal intensity threshold
threshold: 200

# Configure smoothing
smooth:
  iters: 7
  radius: [0, 1, 0]

# Configure apex coordinate adjustment by weighted mean
weighted_mean:
  radius: [2, 10, 0]
